### ISSUE TITLE
"sys" module is now called "util"

### ISSUE THREAD

**Issue by paularmstrong** [tav/nodelint#17] opened 2011-10-12 04:55 UTC
References to the module `sys` should be replaced with `util`, as `sys` has been renamed. Any time you reference it, node.js will return the following warning:

```
The "sys" module is now called "util". It should have a similar interface.
```

_Edit: this log is thrown in node v0.5.9 and will likely also be present in v0.6.0, as they're in final testing now_

**Comment by nelstrom** [comment] 2012-02-08 21:51
Sorry to bring this up again, but I've been seeing the message `The "sys" module is now called "util". It should have a similar interface.` every time that I run nodelint with node v0.6.x.

I just tried installing node v0.4.12, and found that the message no longer appeared. Is it worth re-opening this issue, or are  other 0.6.x compatibility problems the cause?

**Comment by Sannis** [comment] 2012-02-18 23:32
Now fixed.

**Closed as completed by Sannis** 2012-02-18 23:32 UTC

**Comment by nelstrom** [comment] 2012-02-27 20:20
Affirmative, thanks.
